export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';

export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';

export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SECCESS';

export const REMOVE_TASK_START = 'REMOVE_TASK_START';
export const REMOVE_TASK_FAIL = 'REMOVE_TASK_FAIL';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const ON_CHECK_START = 'ON_CHECK_START';
export const ON_CHECK_FAIL = 'ON_CHECK_FAIL';
export const ON_CHECK_SUCCESS = 'ON_CHECK_SUCCESS';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOG_IN_START = 'LOG_IN_START';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const FOUND_EMAIL_START = 'FOUND_EMAIL_START';
export const FOUND_EMAIL_FAIL = 'FOUND_EMAIL_FAIL';
export const FOUND_EMAIL_SUCCESS = 'FOUND_EMAIL_SUCCESS';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_TASK_ERROR = 'CLEAR_TASK_ERROR';
export const CLEAR_EMAIL_ERROR = 'CLEAR_EMAIL_ERROR';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const LOG_IN_GOOGLE = 'LOG_IN_GOOGLE';

export const LOG_OUT = 'LOG_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_TASKS = 'SET_TASKS';
